### ISSUE TITLE
Prefix for the hyperlink

### ISSUE THREAD

**Issue by HT-Moh** [kyoncy/react-markdown-heading#20]
Hi 
I am using [rich-markdown-editor ](https://github.com/outline/rich-markdown-editor) and it generates by default the following html for the headers ex: 
`<h2><button type="button" class="heading-anchor">#</button><span class="heading-content">Introduction</span></h2>`

I can navigate to the headers 
using the link `http://localhost:3000/blog/post-01/#h-introduction`, this link is prefixed with `h-` by default. 
My suggestion is to add `hyperLinkPrefix` to the props, which more less will be implemented as blankSpaceReplaceText, and the line 19 on `parseText.ts` becomes
`${hyperlinkPrefix}${text.replace(/\s+/g, blankSpaceReplaceText)}
`

**Comment by kyoncy** [comment]
@HT-Moh 
Thank you for your good request !
Released a new minor version !

https://www.npmjs.com/package/react-markdown-heading/v/1.2.0

**Comment by HT-Moh** [comment]
@kyoncy your are welcome, I end up adding one more prop, because in the HTML generated the first letter is upper case, but the link is working only lower case. 
```
interface ReactMarkdownHeadingProps {
  markdown: string;
  ulClassName?: string;
  liClassName?: string;
  anchorClassName?: string;
  hyperlink?: boolean;
  blankSpaceReplaceText?: string;
  hyperlinkPrefix?: string;
  hyperlinkLowerCase?: boolean;
  headingDepth?: 1 | 2 | 3 | 4 | 5 | 6;
}
```

```
import { PhrasingContent } from 'mdast';

const parseText = (
  content: PhrasingContent,
  link: {
    text: string;
    href: string;
  },
  blankSpaceReplaceText = '-',
  hyperlinkPrefix: string,
  hyperlinkLowerCase = false
): {
  text: string;
  href: string;
} => {
  switch (content.type) {
    case 'text':
    case 'inlineCode': {
      const text = content.value;
      const href = `${hyperlinkPrefix}${text.replace(
        /\s+/g,
        blankSpaceReplaceText
      )}`;
      link.text += text;

      link.href += hyperlinkLowerCase ? href.toLowerCase() : href;
      break;
    }
    case 'link':
    case 'strong':
    case 'emphasis':
      return content.children.length
        ? parseText(
            content.children[0],
            link,
            blankSpaceReplaceText,
            hyperlinkPrefix,
            hyperlinkLowerCase
          )
        : link;
    default:
      break;
  }

  return link;
};

export default parseText;

```
this works for me now.
